import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "600"],
});

import "@rainbow-me/rainbowkit/styles.css";
import { Providers } from "./providers";
import Navbar from "@/components/fragments/Navbar";

export const metadata: Metadata = {
  title: "N.FesT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakarta.className} bg-gradient-to-r from-[#030303] to-[#111340]`}
      >
        {/* <Navbar></Navbar> */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
